#
# MIT License
#
# Copyright (c) 2017 Choko (choko@curioswitch.org)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
---
steps:
- id: refresh-build-image
  waitFor:
  - '-'
  name: gcr.io/cloud-builders/docker
  args:
  - build
  - --build-arg=cluster=$PROJECT_ID
  - --tag=gcr.io/$PROJECT_ID/java-cloud-builder:latest
  - --file=./tools/build-images/java-cloud-builder/Dockerfile
  - .
  env:
  - CI=true
- id: login-to-cluster
  waitFor:
  - '-'
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
  - -c
  - "gsutil cp gs://curioswitch-cluster-kubepush-key/kubepush.json . \ngcloud auth\
    \ activate-service-account --key-file ./kubepush.json \ngcloud container clusters\
    \ get-credentials curioswitch-cluster --zone asia-northeast1-a"
  env:
  - CLOUDSDK_CONTAINER_USE_CLIENT_CERTIFICATE=True
  - KUBECONFIG=/workspace/kubeconfig
- id: build-curio-auth-server-dist
  waitFor:
  - refresh-build-image
  name: gcr.io/$PROJECT_ID/java-cloud-builder:latest
  entrypoint: ./gradlew
  args:
  - :auth:server:dockerDistTar
  env:
  - CI=true
- id: build-curio-auth-server-image
  waitFor:
  - build-curio-auth-server-dist
  name: gcr.io/cloud-builders/docker
  args:
  - build
  - --tag=asia.gcr.io/$PROJECT_ID/curio-auth-server:latest
  - auth/server/build/docker
  env:
  - CI=true
- id: push-curio-auth-server-image
  waitFor:
  - build-curio-auth-server-image
  name: gcr.io/cloud-builders/docker
  args:
  - push
  - asia.gcr.io/$PROJECT_ID/curio-auth-server:latest
  env:
  - CI=true
- id: deploy-curio-auth-server
  waitFor:
  - push-curio-auth-server-image
  - login-to-cluster
  name: gcr.io/$PROJECT_ID/java-cloud-builder:latest
  entrypoint: ./gradlew
  args:
  - :auth:server:deployAlpha
  env:
  - KUBECONFIG=/workspace/kubeconfig
images:
- gcr.io/$PROJECT_ID/java-cloud-builder:latest
