#
# MIT License
#
# Copyright (c) 2017 Choko (choko@curioswitch.org)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
---
steps:
- id: curio-generated-deepen-git-repo
  waitFor:
  - '-'
  name: gcr.io/cloud-builders/git
  args:
  - fetch
  - origin
  - master
  - --depth=10
  env:
  - CI=true
- id: curio-generated-fetch-build-cache
  waitFor:
  - '-'
  name: gcr.io/cloud-builders/gsutil
  args:
  - cp
  - gs://curioswitch-gradle-build-cache/cloudbuild-cache.tar.gz
  - .gradle/cloudbuild-cache.tar
- id: curio-generated-build-all
  waitFor:
  - curio-generated-deepen-git-repo
  - curio-generated-fetch-build-cache
  name: openjdk:10-jdk-slim
  entrypoint: bash
  args:
  - -c
  - "(test -e .gradle/cloudbuild-cache.tar && tar -xpPf .gradle/cloudbuild-cache.tar || echo No build cache yet.) && ./gradlew yarn resolveDependencies continuousBuild --stacktrace --no-daemon && tar -cpPf .gradle/cloudbuild-cache.tar /root/.gradle/wrapper /usr/local/share/.cache /root/.gradle/caches /root/.gradle/curiostack"
  env:
  - CI=true
  - CI_MASTER=true
- id: curio-generated-update-build-cache
  waitFor:
  - curio-generated-build-all
  name: gcr.io/cloud-builders/gsutil
  args:
  - -o
  - GSUtil:parallel_composite_upload_threshold=150M
  - cp
  - .gradle/cloudbuild-cache.tar
  - gs://curioswitch-gradle-build-cache/cloudbuild-cache.tar.gz
timeout: 60m
