---
steps:
- id: curio-generated-deepen-git-repo
  waitFor:
  - '-'
  name: gcr.io/cloud-builders/git
  args:
  - fetch
  - origin
  - master
  - --depth=10
  env:
  - CI=true
- id: curio-generated-fetch-uncompressed-build-cache
  waitFor:
  - '-'
  name: gcr.io/cloud-builders/gsutil
  entrypoint: bash
  args:
  - -c
  - gsutil cp gs://curioswitch-gradle-build-cache/cloudbuild-cache-uncompressed.tar .gradle/cloudbuild-cache-uncompressed.tar || echo Could not fetch uncompressed build cache...
  env:
  - CI=true
- id: curio-generated-fetch-compressed-build-cache
  waitFor:
  - '-'
  name: gcr.io/cloud-builders/gsutil
  entrypoint: bash
  args:
  - -c
  - gsutil cp gs://curioswitch-gradle-build-cache/cloudbuild-cache-compressed.tar.gz .gradle/cloudbuild-cache-compressed.tar.gz || echo Could not fetch compressed build cache...
  env:
  - CI=true
- id: curio-generated-build-all
  waitFor:
  - curio-generated-deepen-git-repo
  - curio-generated-fetch-uncompressed-build-cache
  - curio-generated-fetch-compressed-build-cache
  name: openjdk:10-jdk-slim
  entrypoint: bash
  args:
  - -c
  - (test -e .gradle/cloudbuild-cache-uncompressed.tar && tar -xpPf .gradle/cloudbuild-cache-uncompressed.tar && tar -xpPf .gradle/cloudbuild-cache-compressed.tar.gz || echo No build cache yet.) && ./gradlew continuousBuild --stacktrace --no-daemon -Pcuriostack.revisionId=$REVISION_ID && tar -cpPf .gradle/cloudbuild-cache-uncompressed.tar /root/.gradle/wrapper /root/.gradle/caches /root/.gradle/curiostack && tar -cpPzf .gradle/cloudbuild-cache-compressed.tar.gz /usr/local/share/.cache
  env:
  - CI=true
  - CI_MASTER=true
  - CLOUDSDK_COMPUTE_ZONE=asia-northeast1
- id: curio-generated-push-uncompressed-build-cache
  waitFor:
  - curio-generated-build-all
  name: gcr.io/cloud-builders/gsutil
  args:
  - -o
  - GSUtil:parallel_composite_upload_threshold=150M
  - cp
  - .gradle/cloudbuild-cache-uncompressed.tar
  - gs://curioswitch-gradle-build-cache/cloudbuild-cache-uncompressed.tar
  env:
  - CI=true
- id: curio-generated-push-compressed-build-cache
  waitFor:
  - curio-generated-build-all
  name: gcr.io/cloud-builders/gsutil
  args:
  - -o
  - GSUtil:parallel_composite_upload_threshold=150M
  - cp
  - .gradle/cloudbuild-cache-compressed.tar.gz
  - gs://curioswitch-gradle-build-cache/cloudbuild-cache-compressed.tar.gz
  env:
  - CI=true
timeout: 60m
