/*
 * This file is generated by jOOQ.
 */
package org.curioswitch.database.cafemapdb.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IFlywaySchemaHistory extends Serializable {

    /**
     * Getter for <code>cafemapdb.flyway_schema_history.installed_rank</code>.
     */
    public Integer getInstalledRank();

    /**
     * Getter for <code>cafemapdb.flyway_schema_history.version</code>.
     */
    public String getVersion();

    /**
     * Getter for <code>cafemapdb.flyway_schema_history.description</code>.
     */
    public String getDescription();

    /**
     * Getter for <code>cafemapdb.flyway_schema_history.type</code>.
     */
    public String getType();

    /**
     * Getter for <code>cafemapdb.flyway_schema_history.script</code>.
     */
    public String getScript();

    /**
     * Getter for <code>cafemapdb.flyway_schema_history.checksum</code>.
     */
    public Integer getChecksum();

    /**
     * Getter for <code>cafemapdb.flyway_schema_history.installed_by</code>.
     */
    public String getInstalledBy();

    /**
     * Getter for <code>cafemapdb.flyway_schema_history.installed_on</code>.
     */
    public LocalDateTime getInstalledOn();

    /**
     * Getter for <code>cafemapdb.flyway_schema_history.execution_time</code>.
     */
    public Integer getExecutionTime();

    /**
     * Getter for <code>cafemapdb.flyway_schema_history.success</code>.
     */
    public Byte getSuccess();
}
