/*
 * MIT License
 *
 * Copyright (c) 2020 Choko (choko@curioswitch.org)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
/*
 * This file is generated by jOOQ.
 */
package org.curioswitch.database.cafemapdb.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IFlywaySchemaHistory extends Serializable {

    /**
     * Getter for <code>cafemapdb.flyway_schema_history.installed_rank</code>.
     */
    public Integer getInstalledRank();

    /**
     * Getter for <code>cafemapdb.flyway_schema_history.version</code>.
     */
    public String getVersion();

    /**
     * Getter for <code>cafemapdb.flyway_schema_history.description</code>.
     */
    public String getDescription();

    /**
     * Getter for <code>cafemapdb.flyway_schema_history.type</code>.
     */
    public String getType();

    /**
     * Getter for <code>cafemapdb.flyway_schema_history.script</code>.
     */
    public String getScript();

    /**
     * Getter for <code>cafemapdb.flyway_schema_history.checksum</code>.
     */
    public Integer getChecksum();

    /**
     * Getter for <code>cafemapdb.flyway_schema_history.installed_by</code>.
     */
    public String getInstalledBy();

    /**
     * Getter for <code>cafemapdb.flyway_schema_history.installed_on</code>.
     */
    public LocalDateTime getInstalledOn();

    /**
     * Getter for <code>cafemapdb.flyway_schema_history.execution_time</code>.
     */
    public Integer getExecutionTime();

    /**
     * Getter for <code>cafemapdb.flyway_schema_history.success</code>.
     */
    public Byte getSuccess();
}
