/*
 * This file is generated by jOOQ.
 */
package org.curioswitch.database.cafemapdb.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ILandmark extends Serializable {

    /**
     * Getter for <code>cafemapdb.landmark.id</code>.
     */
    public ULong getId();

    /**
     * Getter for <code>cafemapdb.landmark.google_place_id</code>.
     */
    public String getGooglePlaceId();

    /**
     * Getter for <code>cafemapdb.landmark.s2_cell</code>.
     */
    public String getS2Cell();

    /**
     * Getter for <code>cafemapdb.landmark.type</code>.
     */
    public String getType();

    /**
     * Getter for <code>cafemapdb.landmark.created_at</code>.
     */
    public LocalDateTime getCreatedAt();

    /**
     * Getter for <code>cafemapdb.landmark.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt();
}
