// flow-typed signature: 7e501b39408f6db40309dd66b1fe6d9b
// flow-typed version: <<STUB>>/html-loader_v0.4.5/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html-loader/lib/attributesParser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html-loader/index' {
  declare module.exports: $Exports<'html-loader'>;
}
declare module 'html-loader/index.js' {
  declare module.exports: $Exports<'html-loader'>;
}
declare module 'html-loader/lib/attributesParser.js' {
  declare module.exports: $Exports<'html-loader/lib/attributesParser'>;
}
