// flow-typed signature: 78b43ba161e2c19f2408a7ab8ef3f26a
// flow-typed version: <<STUB>>/sanitize.css_v5.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}
