// flow-typed signature: d74a38cfa1307c7b70a4124544c9a1d5
// flow-typed version: <<STUB>>/curioswitch-eggworld-api_vfile:../../api/build/web/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'curioswitch-eggworld-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'curioswitch-eggworld-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'curioswitch-eggworld-api/curioswitch/eggworld/eggworld-service_pb_service' {
  declare module.exports: any;
}

declare module 'curioswitch-eggworld-api/curioswitch/eggworld/eggworld-service_pb' {
  declare module.exports: any;
}

// Filename aliases
declare module 'curioswitch-eggworld-api/curioswitch/eggworld/eggworld-service_pb_service.js' {
  declare module.exports: $Exports<'curioswitch-eggworld-api/curioswitch/eggworld/eggworld-service_pb_service'>;
}
declare module 'curioswitch-eggworld-api/curioswitch/eggworld/eggworld-service_pb.js' {
  declare module.exports: $Exports<'curioswitch-eggworld-api/curioswitch/eggworld/eggworld-service_pb'>;
}
declare module 'curioswitch-eggworld-api/index' {
  declare module.exports: $Exports<'curioswitch-eggworld-api'>;
}
declare module 'curioswitch-eggworld-api/index.js' {
  declare module.exports: $Exports<'curioswitch-eggworld-api'>;
}
