// flow-typed signature: 2a046e4b716225d33c9c9cfaf6c29034
// flow-typed version: <<STUB>>/konva_v1.6.7/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'konva'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'konva' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'konva/konva' {
  declare module.exports: any;
}

declare module 'konva/konva.min' {
  declare module.exports: any;
}

declare module 'konva/src/Animation' {
  declare module.exports: any;
}

declare module 'konva/src/BaseLayer' {
  declare module.exports: any;
}

declare module 'konva/src/Canvas' {
  declare module.exports: any;
}

declare module 'konva/src/Container' {
  declare module.exports: any;
}

declare module 'konva/src/Context' {
  declare module.exports: any;
}

declare module 'konva/src/Core' {
  declare module.exports: any;
}

declare module 'konva/src/DragAndDrop' {
  declare module.exports: any;
}

declare module 'konva/src/Factory' {
  declare module.exports: any;
}

declare module 'konva/src/FastLayer' {
  declare module.exports: any;
}

declare module 'konva/src/filters/Blur' {
  declare module.exports: any;
}

declare module 'konva/src/filters/Brighten' {
  declare module.exports: any;
}

declare module 'konva/src/filters/Emboss' {
  declare module.exports: any;
}

declare module 'konva/src/filters/Enhance' {
  declare module.exports: any;
}

declare module 'konva/src/filters/Grayscale' {
  declare module.exports: any;
}

declare module 'konva/src/filters/HSL' {
  declare module.exports: any;
}

declare module 'konva/src/filters/HSV' {
  declare module.exports: any;
}

declare module 'konva/src/filters/Invert' {
  declare module.exports: any;
}

declare module 'konva/src/filters/Kaleidoscope' {
  declare module.exports: any;
}

declare module 'konva/src/filters/Mask' {
  declare module.exports: any;
}

declare module 'konva/src/filters/Noise' {
  declare module.exports: any;
}

declare module 'konva/src/filters/Pixelate' {
  declare module.exports: any;
}

declare module 'konva/src/filters/Posterize' {
  declare module.exports: any;
}

declare module 'konva/src/filters/RGB' {
  declare module.exports: any;
}

declare module 'konva/src/filters/RGBA' {
  declare module.exports: any;
}

declare module 'konva/src/filters/Sepia' {
  declare module.exports: any;
}

declare module 'konva/src/filters/Solarize' {
  declare module.exports: any;
}

declare module 'konva/src/filters/Threshold' {
  declare module.exports: any;
}

declare module 'konva/src/Global' {
  declare module.exports: any;
}

declare module 'konva/src/Group' {
  declare module.exports: any;
}

declare module 'konva/src/Layer' {
  declare module.exports: any;
}

declare module 'konva/src/Node' {
  declare module.exports: any;
}

declare module 'konva/src/Shape' {
  declare module.exports: any;
}

declare module 'konva/src/shapes/Arc' {
  declare module.exports: any;
}

declare module 'konva/src/shapes/Arrow' {
  declare module.exports: any;
}

declare module 'konva/src/shapes/Circle' {
  declare module.exports: any;
}

declare module 'konva/src/shapes/Ellipse' {
  declare module.exports: any;
}

declare module 'konva/src/shapes/Image' {
  declare module.exports: any;
}

declare module 'konva/src/shapes/Label' {
  declare module.exports: any;
}

declare module 'konva/src/shapes/Line' {
  declare module.exports: any;
}

declare module 'konva/src/shapes/Path' {
  declare module.exports: any;
}

declare module 'konva/src/shapes/Rect' {
  declare module.exports: any;
}

declare module 'konva/src/shapes/RegularPolygon' {
  declare module.exports: any;
}

declare module 'konva/src/shapes/Ring' {
  declare module.exports: any;
}

declare module 'konva/src/shapes/Sprite' {
  declare module.exports: any;
}

declare module 'konva/src/shapes/Star' {
  declare module.exports: any;
}

declare module 'konva/src/shapes/Text' {
  declare module.exports: any;
}

declare module 'konva/src/shapes/TextPath' {
  declare module.exports: any;
}

declare module 'konva/src/shapes/Wedge' {
  declare module.exports: any;
}

declare module 'konva/src/Stage' {
  declare module.exports: any;
}

declare module 'konva/src/Tween' {
  declare module.exports: any;
}

declare module 'konva/src/Util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'konva/konva.js' {
  declare module.exports: $Exports<'konva/konva'>;
}
declare module 'konva/konva.min.js' {
  declare module.exports: $Exports<'konva/konva.min'>;
}
declare module 'konva/src/Animation.js' {
  declare module.exports: $Exports<'konva/src/Animation'>;
}
declare module 'konva/src/BaseLayer.js' {
  declare module.exports: $Exports<'konva/src/BaseLayer'>;
}
declare module 'konva/src/Canvas.js' {
  declare module.exports: $Exports<'konva/src/Canvas'>;
}
declare module 'konva/src/Container.js' {
  declare module.exports: $Exports<'konva/src/Container'>;
}
declare module 'konva/src/Context.js' {
  declare module.exports: $Exports<'konva/src/Context'>;
}
declare module 'konva/src/Core.js' {
  declare module.exports: $Exports<'konva/src/Core'>;
}
declare module 'konva/src/DragAndDrop.js' {
  declare module.exports: $Exports<'konva/src/DragAndDrop'>;
}
declare module 'konva/src/Factory.js' {
  declare module.exports: $Exports<'konva/src/Factory'>;
}
declare module 'konva/src/FastLayer.js' {
  declare module.exports: $Exports<'konva/src/FastLayer'>;
}
declare module 'konva/src/filters/Blur.js' {
  declare module.exports: $Exports<'konva/src/filters/Blur'>;
}
declare module 'konva/src/filters/Brighten.js' {
  declare module.exports: $Exports<'konva/src/filters/Brighten'>;
}
declare module 'konva/src/filters/Emboss.js' {
  declare module.exports: $Exports<'konva/src/filters/Emboss'>;
}
declare module 'konva/src/filters/Enhance.js' {
  declare module.exports: $Exports<'konva/src/filters/Enhance'>;
}
declare module 'konva/src/filters/Grayscale.js' {
  declare module.exports: $Exports<'konva/src/filters/Grayscale'>;
}
declare module 'konva/src/filters/HSL.js' {
  declare module.exports: $Exports<'konva/src/filters/HSL'>;
}
declare module 'konva/src/filters/HSV.js' {
  declare module.exports: $Exports<'konva/src/filters/HSV'>;
}
declare module 'konva/src/filters/Invert.js' {
  declare module.exports: $Exports<'konva/src/filters/Invert'>;
}
declare module 'konva/src/filters/Kaleidoscope.js' {
  declare module.exports: $Exports<'konva/src/filters/Kaleidoscope'>;
}
declare module 'konva/src/filters/Mask.js' {
  declare module.exports: $Exports<'konva/src/filters/Mask'>;
}
declare module 'konva/src/filters/Noise.js' {
  declare module.exports: $Exports<'konva/src/filters/Noise'>;
}
declare module 'konva/src/filters/Pixelate.js' {
  declare module.exports: $Exports<'konva/src/filters/Pixelate'>;
}
declare module 'konva/src/filters/Posterize.js' {
  declare module.exports: $Exports<'konva/src/filters/Posterize'>;
}
declare module 'konva/src/filters/RGB.js' {
  declare module.exports: $Exports<'konva/src/filters/RGB'>;
}
declare module 'konva/src/filters/RGBA.js' {
  declare module.exports: $Exports<'konva/src/filters/RGBA'>;
}
declare module 'konva/src/filters/Sepia.js' {
  declare module.exports: $Exports<'konva/src/filters/Sepia'>;
}
declare module 'konva/src/filters/Solarize.js' {
  declare module.exports: $Exports<'konva/src/filters/Solarize'>;
}
declare module 'konva/src/filters/Threshold.js' {
  declare module.exports: $Exports<'konva/src/filters/Threshold'>;
}
declare module 'konva/src/Global.js' {
  declare module.exports: $Exports<'konva/src/Global'>;
}
declare module 'konva/src/Group.js' {
  declare module.exports: $Exports<'konva/src/Group'>;
}
declare module 'konva/src/Layer.js' {
  declare module.exports: $Exports<'konva/src/Layer'>;
}
declare module 'konva/src/Node.js' {
  declare module.exports: $Exports<'konva/src/Node'>;
}
declare module 'konva/src/Shape.js' {
  declare module.exports: $Exports<'konva/src/Shape'>;
}
declare module 'konva/src/shapes/Arc.js' {
  declare module.exports: $Exports<'konva/src/shapes/Arc'>;
}
declare module 'konva/src/shapes/Arrow.js' {
  declare module.exports: $Exports<'konva/src/shapes/Arrow'>;
}
declare module 'konva/src/shapes/Circle.js' {
  declare module.exports: $Exports<'konva/src/shapes/Circle'>;
}
declare module 'konva/src/shapes/Ellipse.js' {
  declare module.exports: $Exports<'konva/src/shapes/Ellipse'>;
}
declare module 'konva/src/shapes/Image.js' {
  declare module.exports: $Exports<'konva/src/shapes/Image'>;
}
declare module 'konva/src/shapes/Label.js' {
  declare module.exports: $Exports<'konva/src/shapes/Label'>;
}
declare module 'konva/src/shapes/Line.js' {
  declare module.exports: $Exports<'konva/src/shapes/Line'>;
}
declare module 'konva/src/shapes/Path.js' {
  declare module.exports: $Exports<'konva/src/shapes/Path'>;
}
declare module 'konva/src/shapes/Rect.js' {
  declare module.exports: $Exports<'konva/src/shapes/Rect'>;
}
declare module 'konva/src/shapes/RegularPolygon.js' {
  declare module.exports: $Exports<'konva/src/shapes/RegularPolygon'>;
}
declare module 'konva/src/shapes/Ring.js' {
  declare module.exports: $Exports<'konva/src/shapes/Ring'>;
}
declare module 'konva/src/shapes/Sprite.js' {
  declare module.exports: $Exports<'konva/src/shapes/Sprite'>;
}
declare module 'konva/src/shapes/Star.js' {
  declare module.exports: $Exports<'konva/src/shapes/Star'>;
}
declare module 'konva/src/shapes/Text.js' {
  declare module.exports: $Exports<'konva/src/shapes/Text'>;
}
declare module 'konva/src/shapes/TextPath.js' {
  declare module.exports: $Exports<'konva/src/shapes/TextPath'>;
}
declare module 'konva/src/shapes/Wedge.js' {
  declare module.exports: $Exports<'konva/src/shapes/Wedge'>;
}
declare module 'konva/src/Stage.js' {
  declare module.exports: $Exports<'konva/src/Stage'>;
}
declare module 'konva/src/Tween.js' {
  declare module.exports: $Exports<'konva/src/Tween'>;
}
declare module 'konva/src/Util.js' {
  declare module.exports: $Exports<'konva/src/Util'>;
}
