// flow-typed signature: 9217d5ecfeae4f91efff4068ed26cf9e
// flow-typed version: <<STUB>>/react-konva_v1.1.4/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-konva'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-konva' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-konva/src/react-konva' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-konva/src/react-konva.js' {
  declare module.exports: $Exports<'react-konva/src/react-konva'>;
}
