/*
 * This file is generated by jOOQ.
 */
package org.curioswitch.database.cafemapdb.tables.records;


import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.curioswitch.database.cafemapdb.tables.Place;
import org.curioswitch.database.cafemapdb.tables.interfaces.IPlace;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlaceRecord extends UpdatableRecordImpl<PlaceRecord> implements Record9<ULong, String, Double, Double, ULong, String, String, LocalDateTime, LocalDateTime>, IPlace {

    private static final long serialVersionUID = -765215836;

    /**
     * Setter for <code>cafemapdb.place.id</code>.
     */
    public PlaceRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>cafemapdb.place.id</code>.
     */
    @Override
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>cafemapdb.place.name</code>.
     */
    public PlaceRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>cafemapdb.place.name</code>.
     */
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cafemapdb.place.latitude</code>.
     */
    public PlaceRecord setLatitude(Double value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>cafemapdb.place.latitude</code>.
     */
    @Override
    public Double getLatitude() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>cafemapdb.place.longitude</code>.
     */
    public PlaceRecord setLongitude(Double value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>cafemapdb.place.longitude</code>.
     */
    @Override
    public Double getLongitude() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>cafemapdb.place.s2_cell</code>.
     */
    public PlaceRecord setS2Cell(ULong value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>cafemapdb.place.s2_cell</code>.
     */
    @Override
    public ULong getS2Cell() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>cafemapdb.place.instagram_id</code>.
     */
    public PlaceRecord setInstagramId(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>cafemapdb.place.instagram_id</code>.
     */
    @Override
    public String getInstagramId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>cafemapdb.place.google_place_id</code>.
     */
    public PlaceRecord setGooglePlaceId(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>cafemapdb.place.google_place_id</code>.
     */
    @Override
    public String getGooglePlaceId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>cafemapdb.place.created_at</code>.
     */
    public PlaceRecord setCreatedAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>cafemapdb.place.created_at</code>.
     */
    @Override
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>cafemapdb.place.updated_at</code>.
     */
    public PlaceRecord setUpdatedAt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>cafemapdb.place.updated_at</code>.
     */
    @Override
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<ULong, String, Double, Double, ULong, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<ULong, String, Double, Double, ULong, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return Place.PLACE.ID;
    }

    @Override
    public Field<String> field2() {
        return Place.PLACE.NAME;
    }

    @Override
    public Field<Double> field3() {
        return Place.PLACE.LATITUDE;
    }

    @Override
    public Field<Double> field4() {
        return Place.PLACE.LONGITUDE;
    }

    @Override
    public Field<ULong> field5() {
        return Place.PLACE.S2_CELL;
    }

    @Override
    public Field<String> field6() {
        return Place.PLACE.INSTAGRAM_ID;
    }

    @Override
    public Field<String> field7() {
        return Place.PLACE.GOOGLE_PLACE_ID;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Place.PLACE.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return Place.PLACE.UPDATED_AT;
    }

    @Override
    public ULong component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Double component3() {
        return getLatitude();
    }

    @Override
    public Double component4() {
        return getLongitude();
    }

    @Override
    public ULong component5() {
        return getS2Cell();
    }

    @Override
    public String component6() {
        return getInstagramId();
    }

    @Override
    public String component7() {
        return getGooglePlaceId();
    }

    @Override
    public LocalDateTime component8() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component9() {
        return getUpdatedAt();
    }

    @Override
    public ULong value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Double value3() {
        return getLatitude();
    }

    @Override
    public Double value4() {
        return getLongitude();
    }

    @Override
    public ULong value5() {
        return getS2Cell();
    }

    @Override
    public String value6() {
        return getInstagramId();
    }

    @Override
    public String value7() {
        return getGooglePlaceId();
    }

    @Override
    public LocalDateTime value8() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value9() {
        return getUpdatedAt();
    }

    @Override
    public PlaceRecord value1(ULong value) {
        setId(value);
        return this;
    }

    @Override
    public PlaceRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public PlaceRecord value3(Double value) {
        setLatitude(value);
        return this;
    }

    @Override
    public PlaceRecord value4(Double value) {
        setLongitude(value);
        return this;
    }

    @Override
    public PlaceRecord value5(ULong value) {
        setS2Cell(value);
        return this;
    }

    @Override
    public PlaceRecord value6(String value) {
        setInstagramId(value);
        return this;
    }

    @Override
    public PlaceRecord value7(String value) {
        setGooglePlaceId(value);
        return this;
    }

    @Override
    public PlaceRecord value8(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public PlaceRecord value9(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public PlaceRecord values(ULong value1, String value2, Double value3, Double value4, ULong value5, String value6, String value7, LocalDateTime value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    public void from(IPlace from) {
        setId(from.getId());
        setName(from.getName());
        setLatitude(from.getLatitude());
        setLongitude(from.getLongitude());
        setS2Cell(from.getS2Cell());
        setInstagramId(from.getInstagramId());
        setGooglePlaceId(from.getGooglePlaceId());
        setCreatedAt(from.getCreatedAt());
        setUpdatedAt(from.getUpdatedAt());
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlaceRecord
     */
    public PlaceRecord() {
        super(Place.PLACE);
    }

    /**
     * Create a detached, initialised PlaceRecord
     */
    public PlaceRecord(ULong id, String name, Double latitude, Double longitude, ULong s2Cell, String instagramId, String googlePlaceId, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Place.PLACE);

        set(0, id);
        set(1, name);
        set(2, latitude);
        set(3, longitude);
        set(4, s2Cell);
        set(5, instagramId);
        set(6, googlePlaceId);
        set(7, createdAt);
        set(8, updatedAt);
    }
}
