/*
 * This file is generated by jOOQ.
 */
package org.curioswitch.database.cafemapdb.tables.records;


import javax.annotation.Generated;

import org.curioswitch.database.cafemapdb.tables.Place;
import org.curioswitch.database.cafemapdb.tables.interfaces.IPlace;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlaceRecord extends UpdatableRecordImpl<PlaceRecord> implements Record5<ULong, String, Double, Double, String>, IPlace {

    private static final long serialVersionUID = -2070012994;

    /**
     * Setter for <code>cafemapdb.place.id</code>.
     */
    public PlaceRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>cafemapdb.place.id</code>.
     */
    @Override
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>cafemapdb.place.name</code>.
     */
    public PlaceRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>cafemapdb.place.name</code>.
     */
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cafemapdb.place.latitude</code>.
     */
    public PlaceRecord setLatitude(Double value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>cafemapdb.place.latitude</code>.
     */
    @Override
    public Double getLatitude() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>cafemapdb.place.longitude</code>.
     */
    public PlaceRecord setLongitude(Double value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>cafemapdb.place.longitude</code>.
     */
    @Override
    public Double getLongitude() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>cafemapdb.place.instagram_id</code>.
     */
    public PlaceRecord setInstagramId(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>cafemapdb.place.instagram_id</code>.
     */
    @Override
    public String getInstagramId() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<ULong, String, Double, Double, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<ULong, String, Double, Double, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return Place.PLACE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Place.PLACE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return Place.PLACE.LATITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return Place.PLACE.LONGITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Place.PLACE.INSTAGRAM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getInstagramId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getInstagramId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlaceRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlaceRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlaceRecord value3(Double value) {
        setLatitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlaceRecord value4(Double value) {
        setLongitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlaceRecord value5(String value) {
        setInstagramId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlaceRecord values(ULong value1, String value2, Double value3, Double value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    public void from(IPlace from) {
        setId(from.getId());
        setName(from.getName());
        setLatitude(from.getLatitude());
        setLongitude(from.getLongitude());
        setInstagramId(from.getInstagramId());
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlaceRecord
     */
    public PlaceRecord() {
        super(Place.PLACE);
    }

    /**
     * Create a detached, initialised PlaceRecord
     */
    public PlaceRecord(ULong id, String name, Double latitude, Double longitude, String instagramId) {
        super(Place.PLACE);

        set(0, id);
        set(1, name);
        set(2, latitude);
        set(3, longitude);
        set(4, instagramId);
    }
}
